# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Keep Movin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Keep Movin
  pod 'SteviaLayout'  
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'IQKeyboardManagerSwift'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Protobuf' 

end
